DEFAULT:

  LOG_SETTING:
    LEVEL: info
    FORMAT: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    DATE_FORMAT: '%Y-%m-%d %H:%M:%S %z'

  DATASET:
    CSV_FILES: [ 'Youtube01-Psy.csv',
                 'Youtube02-KatyPerry.csv',
                 'Youtube03-LMFAO.csv',
                 'Youtube04-Eminem.csv',
                 'Youtube05-Shakira.csv',
    ]

  RANDOM_STATE: 42 # set it to zero to disable it

  PREPROCESSING: # change enabled to true and false to disable the component
    DEDUPLICATION_COLUMNS: [ 'COMMENT_ID' ]
    STRIP_TEXT:
      ENABLED: true
    FLAG_YOUTUBE:
      ENABLED: true
    FLAG_URL:
      ENABLED: true
    LOWER_CASE:
      ENABLED: true
    REPLACE_EMOJI:
      ENABLED: false
    REMOVE_SPECIAL_CHARACTERS:
      ENABLED: true
    REMOVE_NUMBERS:
      ENABLED: true
    REMOVE_SHORT_WORD:
      ENABLED: true
    REMOVE_EXTRA_WHITE_SPACE:
      ENABLED: true
    LEMMATIZATION:
      ENABLED: true
      SPACY_MODEL: en_core_web_md
      NUMBER_OF_PROCESS: 1

  MODELING:
    SPACY:
      MODEL: en_core_web_md
      NUMBER_OF_PROCESS: 1
    TF_IDF:
      MAX_DF: 0.65
      MIN_DF: 1
    SPLIT: # sum of the following numbers should be one
      TRAIN: 0.92
      VAL: 0.04
      TEST: 0.04